import Header from '@/components/Header'
import Head from 'next/head'
import React from 'react'
interface dashboardInfo {
    info: string,
    button: boolean,
  }

const dashboard = () => {
    const dashobj = {info: "Dashboard", button: false}
  return (
    <div>    
        <Head>
    <title>Dashboard</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Header {...dashobj} />
  </div>
  )
}

export default dashboard